### ISSUE TITLE
[BUG] - Unable to quit the running task such as "search"

### ISSUE THREAD

**Issue by c02y** [veeso/termscp#116]
## Description

When I connect to my ftp client successfully, I try to search a keyword in it using `F`, but it gets stuck  in the `Searching for "xxx"` window, and I cannot quit the job or use other command like `F10|Q` or `F1|H`, I have to kill termcp process from other temrinal.
## Steps to reproduce

Steps to reproduce the bug you encountered

1. Connect to a client through FTP
2. navigate to the client directory
3. `F` to search something
4. it gets stuck, unable to do anything else, have to kill it in other terminal

## Expected behaviour

It should successfully find or not_find the files/directories instead of getting stuck, and it should not prevent other commands

## Environment

- OS: [e.g. GNU/Linux Debian 10] `Arch Linux`
- Architecture [Arm, x86_64, ...] `x86_x64`
- Rust version: `rustc 1.62.0 (a8314ef7d 2022-06-27)`
- termscp version: `0.9.0`
- Protocol used : `FTP`
- Remote server version and name: `Android Smart Phone, not sure the version and name`

## Log

Report the snippet of the log file containing the unexpected behaviour.
If there is any information you consider to be confidential, shadow it.

**Comment by veeso** [comment]
It's not really a bug, the problem is that currently, the file transfer actions are blocking since everything runs on the same thread.

I've been thinking about refactoring the UI for a long time and putting the file transfer on another thread as a Service, but this would require a huge refactoring and a lot of time, which I'm not going to invest at the moment.

The only thing you can do is to avoid long-time execution searches.
