### ISSUE TITLE
[BUG] - MacOS SSH key auth fails

### ISSUE THREAD

**Issue by MadGhigno** [veeso/termscp#238]
## Description

Trying to access a server using ssh keys results in the following error:   protocol error ([Session(-5)] Unable to exchange encryption keys)

## Steps to reproduce

Configure a server with public/private ssh key authentication and place the configuration in the ~/.ssh/config

Ex:

Host server-test
  HostName [hostname or ip]
  User <username>
  Port <port number>
  IdentityFile  <path to the private key file> 

## Expected behavior

Selecting SCP and typing "server-test" in the [remote host] and hit enter. It is expected to connect to the remote server.
I tried the same thing on a Linux machine and it works as expected. 

## Environment

- OS: MacOS (Sonoma 14.4.1)
- Architecture Apple Silicon
- Rust rustc 1.76.0 (07dca489a 2024-02-04) (Homebrew)
- termscp 0.13.0
- Protocol SCP
- Remote server Ubuntu 22.04.2 LTS

## Log

NA

## Additional information

NA

**Comment by shishkin** [comment]
This is still an issue

**Comment by artawan** [comment]
I got the same issues

Error: `authentication failed ([Session(-18)] Authentication failed (username/password))`

I thought it was an error with the installation method. I did some installation method but the problem is still there.
I'm trying to use ssh command in terminal it's working fine with the same username/password.

### Installation method
CURL
```bash
curl --proto '=https' --tlsv1.2 -sSLf "https://git.io/JBhDb" | sh
```

Cargo install
```bash
cargo install termscp
```

Brew
```bash
brew install veeso/termscp/termscp
```

From Source
```bash
git clone git@github.com:veeso/termscp.git --single-branch -b main
cd termscp
cargo build --release
```
