### ISSUE TITLE
[BUG] - Hidden UI elements when window height is too small

### ISSUE THREAD

**Issue by Markus00000** [veeso/termscp#36]
## Description

If the window height gets too small, elements are hidden without indication (e.g. invisible password field). They can still be accessed with the keyboard and accept inputs.

![Screenshot](https://user-images.githubusercontent.com/985977/119348447-2d402d00-bc9d-11eb-9818-bc44315a2273.png)

## Steps to reproduce

Reduce the window height.

## Expected behaviour

If UI elements do not fit the window, there should be a way to reveal them by scrolling. A scroll indicator should indicate that some elements are not visible.

## Environment

- OS: Arch Linux, i3
- Architecture: x86_64
- termscp version: 0.5.0

**Comment by veeso** [comment]
Unfortunately there's no way to create responsive layouts with tui and there's no scrolling or anything like that. I could implement a component into my framework (tui-realm) to create forms with scrollbars, but it would be overway complicated.

I've checked that with at least a 720p display with.a decent font size for that display (15px) you should display everything fine.
The only thing I could do here is to use absolute sizes for the authentication form instead of the current 70:30 ratio.

The point is that you can't just run tui application on any terminal size, but there are some limitations actually.

I put the relative to absolute sizes change on my agenda, but I've seen that it wouldn't anyway fix your case, so for me this issue is just a wontfix.

**Comment by Markus00000** [comment]
Have you considered displaying a message if the UI does not fit the window?

For example, ncdu shows this:

    Warning: terminal too small,
     please either resize your terminal,
     press i to ignore, or press q to quit.

Such a warning would at least prevent any confusion caused by invisible or partially visible UI elements.

**Comment by veeso** [comment]
Yep, It makes sense, thanks. I'll report it in my agenda

**Comment by veeso** [comment]
Planned for 0.5.1

- Show error message in auth activity when screen is too small.
- Use absolute layout sizes when known

**Comment by veeso** [comment]
Implementation in PR #50 ; merged into 0.5.1 branch
