### ISSUE TITLE
Auth with private key

### ISSUE THREAD

**Issue by mausch** [veeso/termscp#86]
Hi and thank you for this project!

I'm trying to authenticate to a server using a private key, but termscp seems to always ask for a password?
Is it possible to authenticate with a private key? The documentation mentions how to add SSH keys but there doesn't seem to be anything about using them for authenticating.

Many thanks and happy new year!

**Comment by veeso** [comment]
Once you've configured the ssh key in termscp, from the configuration menu, you should be able to connect to that host without any problem. If you use the CLI argument to connect, it'll always ask for a password, even if not necessary (unfortunately, this thing is so by design and I don't know when I'll solve it), so you should just press enter and everything should work.

You're welcome and happy new year to you!

**Comment by mausch** [comment]
Cheers :+1:
